In [2]:
import numpy as np

In [3]:
nums = np.arange(1,6)
print(nums)
print(nums*2)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [4]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
range_arr = np.arange(10)
print(range_arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
ones = np.ones((4,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
spaced = np.linspace(0,1,5)
print(spaced)

[0.   0.25 0.5  0.75 1.  ]


## this is a title
### subtitle
#### sub-subtitle?
<details>
    this is a spoiler
</details>


In [29]:
nums = np.arange(1,10).reshape((3,3))
print(nums)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(nums[0][1])

2


In [19]:
print(nums[:,1])

[2 5 8]


In [20]:
print(nums[:,2])

[3 6 9]


In [21]:
five = np.arange(1,10)[:5]
print(five)

[1 2 3 4 5]


In [23]:
print(nums[:2])

[[1 2 3]
 [4 5 6]]


In [24]:
print(nums[1:,1:])

[[5 6]
 [8 9]]


In [44]:
my_nums = np.arange(1,13).reshape(4,3)
print(my_nums)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
print(my_nums.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [42]:
middle = my_nums[:,1]
print(middle)

[ 2  5  8 11]


In [43]:
print(middle.flatten())

[ 2  5  8 11]


In [51]:
a = np.arange(1,5)
b = np.arange(10,41,10)
print(a,b)

[1 2 3 4] [10 20 30 40]


In [48]:
a + b

array([11, 22, 33, 44])

In [49]:
a-b

array([ -9, -18, -27, -36])

In [52]:
b/a

array([10., 10., 10., 10.])

In [53]:
np.sqrt(b)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [54]:
np.pow(b,2)

array([ 100,  400,  900, 1600])

In [55]:
np.exp(b)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17])

In [56]:
three = np.arange(1,4)
fives = three*5
evens = three*2

In [57]:
fives+evens

array([ 7, 14, 21])

In [58]:
fives-evens

array([3, 6, 9])

In [59]:
fives*evens

array([10, 40, 90])

In [60]:
fives/evens

array([2.5, 2.5, 2.5])

In [61]:
fives**3

array([ 125, 1000, 3375])

In [68]:
my_list = [[y*3 + x for x in range(1,4)] for y in range(3)]
np.ravel(my_list)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr_2d = np.arange(1,7).reshape(2,3)
tens = np.arange(10,31,10)

In [77]:
arr_2d + tens

array([[11, 22, 33],
       [14, 25, 36]])

In [82]:
my_arr = np.arange(2,9,2)*.5
arr_3x3 = np.arange(1,10).reshape(3,3)
arr_3x3 += np.arange(1,4)
arr_2x3 = np.arange(1,7).reshape(2,3)
arr_2x3 += 10

In [83]:
my_arr

array([1., 2., 3., 4.])

In [84]:
arr_3x3

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [85]:
arr_2x3

array([[11, 12, 13],
       [14, 15, 16]])

In [121]:
import time

long_list = [x for x in range(1000000)]
start = time.time()
long_list_mult = list(map(lambda x: x*2, long_list))
end = time.time()
print(end-start)

0.08674931526184082


In [122]:
start = time.time()
long_list_mult = [x*2 for x in long_list]
end = time.time()
print(end-start)

0.06059885025024414


In [123]:
np_long_list = np.array(long_list)
start = time.time()
np_long_mult = np_long_list * 2
end = time.time()
print(end-start)

0.002916097640991211


In [133]:
def timer(func):
    def closure():
        start = time.time()
        func()
        end = time.time()
        print(end-start)
    return closure

timer(lambda : [x*2 for x in long_list])()

0.0604095458984375


In [161]:
print(np.random.randint(1,7, size=10))

[3 0 0 1 1 4 5 4 0 2]


In [167]:
print(np.random.random([5,4]))

[[0.30003104 0.82395615 0.21050204 0.05428387]
 [0.16573435 0.09075541 0.60580888 0.02369287]
 [0.41175391 0.56230769 0.13297474 0.45017871]
 [0.12209962 0.23746638 0.8978963  0.24154334]
 [0.81270895 0.43114819 0.76685519 0.93749937]]


In [170]:
print(np.random.randn((10)))

[ 0.75093286 -0.64510207 -0.11338732  0.6504083  -0.48594455  1.56921171
 -0.75108579  1.89766793  0.02701427 -2.13495186]


In [404]:
dice = np.random.randint(1, 7, 20)
print(min(dice))
print(max(dice))
print(dice)

1
6
[4 4 3 5 4 5 3 1 2 6 2 5 2 5 5 6 2 6 3 6]


In [252]:
rand_arr = np.random.random(10)*10
print(rand_arr)

[2.49986535 6.00979139 1.5857016  9.48781174 8.29791498 1.28483764
 2.25215558 6.8322495  5.51689566 5.84207133]


In [310]:
rand_normal = np.random.randn(1000)
print(rand_normal[:10])

[-0.32547804  0.62155863 -0.9971795   1.1403866  -0.32544441  1.25099368
 -0.37953513  0.11576523 -0.8408661  -0.32555249]


In [484]:
dice = np.random.randint(1, 7, 20)
print(dice.sum())
print(dice.mean())
print(np.median(dice))
print(dice.std())

76
3.8
4.5
1.7776388834631176


In [487]:
rand_50 = np.random.randint(10,101,50)
print(np.sum(rand_50))
print(np.mean(rand_50))
print(np.median(rand_50))
print(np.std(rand_50))

2945
58.9
61.0
28.53927118901252


In [494]:
stack_1 = np.arange(1,11)
stack_2 = np.arange(11,21)
stacked = np.stack((stack_1, stack_2), axis=0)
print(stacked)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [502]:
arr_4x4 = np.random.randint(0,15, 16).reshape(4,4)
print(arr_4x4)

[[11  7  9  6]
 [ 9 13  8 12]
 [ 9  2  0  8]
 [ 5 14  0 11]]


In [500]:
stack_1 = np.arange(1,11)
stack_2 = np.arange(11,21)
print(np.stack((stack_1,stack_2)))
print(np.stack((stack_1,stack_2),axis=1))

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]
 [10 20]]


In [501]:
dice_1 = np.random.randint(1,7,5)
dice_2 = np.random.randint(1,7,5)
dice_stack = np.stack((dice_1,dice_2))
print(dice_stack)
print(dice_stack.shape)

[[5 6 3 3 3]
 [1 5 5 2 1]]
(2, 5)
